type PullRequestSummary = {
  type: "feature" | "fix" | "refactor" | "infra";
  area: string;
  impact: "core" | "edge";
  summary: string;
  teamsAffected: string[];
  reviewFeedbackTone: "positive" | "constructive" | "minimal";
  merged: boolean;
};

type IssueSummary = {
  category: "design discussion" | "bug" | "tech debt" | "proposal";
  summary: string;
  outcome: "accepted" | "deferred" | "rejected";
};

type GithubWeekRow = {
  employeeEmail: string;
  weekStart: string;
  pullRequestSummaries: PullRequestSummary[];
  issueSummaries: IssueSummary[];
  prsMerged: number;
  prReviewsGiven: number;
  afterHoursRatio: number;
  weekendRatio: number;
};

type MessageSummary = {
  theme: string;
  intent: "collaboration" | "support" | "blocking" | "status update" | "passive";
  sentiment: "positive" | "neutral" | "neutral-negative";
  example: string;
};

type SlackWeekRow = {
  employeeEmail: string;
  weekStart: string;
  messageSummaries: MessageSummary[];
  messageCount: number;
  replyCount: number;
  reactionsReceived: number;
  afterHoursRatio: number;
  weekendRatio: number;
};

export const employeesData = [
  {
    name: "Alice",
    email: "alice@company.com",
    role: "AI_ENGINEER",
  },
  {
    name: "Bob",
    email: "bob@company.com",
    role: "AI_ENGINEER",
  },
  {
    name: "Carol",
    email: "carol@company.com",
    role: "AI_ENGINEER",
  },
  {
    name: "Dave",
    email: "dave@company.com",
    role: "AI_ENGINEER",
  },
  {
    name: "Eve",
    email: "eve@company.com",
    role: "AI_ENGINEER",
  },
];

export const githubWeeklyData: GithubWeekRow[] = [
  {
    employeeEmail: "alice@company.com",
    weekStart: "2025-10-06",
    pullRequestSummaries: [
      {
        type: "feature",
        area: "prompt pipeline",
        impact: "edge",
        summary: "Added prompt pre-validation to reduce failed renders in batch campaigns.",
        teamsAffected: ["marketing", "platform"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "fix",
        area: "image rendering",
        impact: "edge",
        summary: "Fixed sporadic timeout handling for high-resolution exports.",
        teamsAffected: ["platform"],
        reviewFeedbackTone: "constructive",
        merged: true,
      },
      {
        type: "refactor",
        area: "usage metering",
        impact: "edge",
        summary: "Simplified usage metering logic to align with new pricing tiers.",
        teamsAffected: ["growth", "platform"],
        reviewFeedbackTone: "positive",
        merged: false,
      },
    ],
    issueSummaries: [
      {
        category: "bug",
        summary: "Reported and scoped a regression in batch export retries.",
        outcome: "accepted",
      },
    ],
    prsMerged: 2,
    prReviewsGiven: 4,
    afterHoursRatio: 0.04,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "alice@company.com",
    weekStart: "2025-10-13",
    pullRequestSummaries: [
      {
        type: "feature",
        area: "campaign scheduler",
        impact: "edge",
        summary:
          "Introduced scheduled campaign windows for time-zone specific launches.",
        teamsAffected: ["marketing", "growth"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "refactor",
        area: "API",
        impact: "edge",
        summary: "Refactored prompt ingestion to support structured attributes.",
        teamsAffected: ["platform"],
        reviewFeedbackTone: "constructive",
        merged: true,
      },
      {
        type: "fix",
        area: "billing",
        impact: "edge",
        summary: "Fixed proration rounding in monthly invoice previews.",
        teamsAffected: ["growth"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "infra",
        area: "CI",
        impact: "edge",
        summary: "Tuned CI steps to reduce image build timeouts.",
        teamsAffected: ["infra", "platform"],
        reviewFeedbackTone: "minimal",
        merged: false,
      },
    ],
    issueSummaries: [
      {
        category: "proposal",
        summary: "Proposed a staged rollout plan for new render presets.",
        outcome: "accepted",
      },
    ],
    prsMerged: 3,
    prReviewsGiven: 5,
    afterHoursRatio: 0.04,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "alice@company.com",
    weekStart: "2025-10-20",
    pullRequestSummaries: [
      {
        type: "feature",
        area: "render orchestration",
        impact: "core",
        summary:
          "Added orchestration guardrails to prevent duplicate render jobs.",
        teamsAffected: ["platform", "infra"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "fix",
        area: "image rendering",
        impact: "edge",
        summary: "Fixed color profile mismatch on social exports.",
        teamsAffected: ["marketing"],
        reviewFeedbackTone: "constructive",
        merged: true,
      },
      {
        type: "refactor",
        area: "prompt pipeline",
        impact: "edge",
        summary:
          "Cleaned up prompt normalization to reduce variability in A/B tests.",
        teamsAffected: ["growth"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "infra",
        area: "metrics",
        impact: "edge",
        summary: "Added dashboard counters for render queue depth.",
        teamsAffected: ["infra", "platform"],
        reviewFeedbackTone: "minimal",
        merged: false,
      },
    ],
    issueSummaries: [
      {
        category: "bug",
        summary: "Logged an intermittent cache invalidation issue on multi-variant renders.",
        outcome: "accepted",
      },
    ],
    prsMerged: 3,
    prReviewsGiven: 6,
    afterHoursRatio: 0.03,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "alice@company.com",
    weekStart: "2025-10-27",
    pullRequestSummaries: [
      {
        type: "feature",
        area: "prompt pipeline",
        impact: "core",
        summary: "Enabled reusable prompt templates for campaign series.",
        teamsAffected: ["marketing", "growth", "platform"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "fix",
        area: "API",
        impact: "core",
        summary: "Resolved idempotency gaps for bulk generation requests.",
        teamsAffected: ["platform", "infra"],
        reviewFeedbackTone: "constructive",
        merged: true,
      },
      {
        type: "refactor",
        area: "billing",
        impact: "edge",
        summary: "Refactored usage aggregation to remove legacy dimensions.",
        teamsAffected: ["growth"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "infra",
        area: "alerts",
        impact: "edge",
        summary: "Added alerting for render latency spikes.",
        teamsAffected: ["infra"],
        reviewFeedbackTone: "minimal",
        merged: true,
      },
    ],
    issueSummaries: [
      {
        category: "proposal",
        summary: "Suggested a gradual shift to prompt quality scoring in the UI.",
        outcome: "accepted",
      },
    ],
    prsMerged: 4,
    prReviewsGiven: 7,
    afterHoursRatio: 0.04,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "alice@company.com",
    weekStart: "2025-11-03",
    pullRequestSummaries: [
      {
        type: "feature",
        area: "image rendering",
        impact: "core",
        summary: "Shipped multi-aspect rendering options for campaign variants.",
        teamsAffected: ["marketing", "growth", "platform"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "fix",
        area: "render queue",
        impact: "core",
        summary: "Fixed queue starvation when long-running jobs accumulate.",
        teamsAffected: ["platform", "infra"],
        reviewFeedbackTone: "constructive",
        merged: true,
      },
      {
        type: "refactor",
        area: "prompt pipeline",
        impact: "core",
        summary: "Modularized prompt transforms for safer experimentation.",
        teamsAffected: ["growth", "platform"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "infra",
        area: "deploy",
        impact: "edge",
        summary: "Improved rollout checks for rendering services.",
        teamsAffected: ["infra"],
        reviewFeedbackTone: "minimal",
        merged: false,
      },
    ],
    issueSummaries: [
      {
        category: "design discussion",
        summary:
          "Opened a discussion on aligning prompt templates with brand guidelines.",
        outcome: "accepted",
      },
    ],
    prsMerged: 3,
    prReviewsGiven: 8,
    afterHoursRatio: 0.03,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "alice@company.com",
    weekStart: "2025-11-10",
    pullRequestSummaries: [
      {
        type: "feature",
        area: "campaign analytics",
        impact: "core",
        summary:
          "Added campaign-level performance snapshots to the dashboard.",
        teamsAffected: ["marketing", "growth", "platform"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "fix",
        area: "API",
        impact: "core",
        summary: "Resolved pagination drift in campaign history endpoints.",
        teamsAffected: ["platform"],
        reviewFeedbackTone: "constructive",
        merged: true,
      },
      {
        type: "refactor",
        area: "image rendering",
        impact: "core",
        summary:
          "Consolidated render presets to reduce duplication across services.",
        teamsAffected: ["platform", "infra"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "infra",
        area: "metrics",
        impact: "edge",
        summary: "Added render success rate SLIs for on-call visibility.",
        teamsAffected: ["infra"],
        reviewFeedbackTone: "minimal",
        merged: true,
      },
      {
        type: "feature",
        area: "prompt pipeline",
        impact: "core",
        summary: "Enabled reusable prompt blocks for multi-channel campaigns.",
        teamsAffected: ["marketing", "growth"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
    ],
    issueSummaries: [
      {
        category: "design discussion",
        summary:
          "Facilitated a thread on separating creative vs. performance prompts.",
        outcome: "accepted",
      },
      {
        category: "bug",
        summary: "Flagged a race condition in campaign exports.",
        outcome: "accepted",
      },
    ],
    prsMerged: 5,
    prReviewsGiven: 9,
    afterHoursRatio: 0.04,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "alice@company.com",
    weekStart: "2025-11-17",
    pullRequestSummaries: [
      {
        type: "feature",
        area: "render orchestration",
        impact: "core",
        summary:
          "Added prioritization controls for high-priority campaign bursts.",
        teamsAffected: ["platform", "infra", "marketing"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "fix",
        area: "billing",
        impact: "core",
        summary: "Fixed overcounting for cancelled render jobs.",
        teamsAffected: ["growth", "platform"],
        reviewFeedbackTone: "constructive",
        merged: true,
      },
      {
        type: "refactor",
        area: "API",
        impact: "core",
        summary: "Standardized API response envelopes for rendering endpoints.",
        teamsAffected: ["platform"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "infra",
        area: "observability",
        impact: "edge",
        summary: "Expanded tracing around render retries.",
        teamsAffected: ["infra"],
        reviewFeedbackTone: "minimal",
        merged: true,
      },
      {
        type: "feature",
        area: "campaign scheduler",
        impact: "core",
        summary: "Added automatic rescheduling for failed campaign runs.",
        teamsAffected: ["marketing", "growth"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
    ],
    issueSummaries: [
      {
        category: "design discussion",
        summary:
          "Captured stakeholder feedback on prompt template discoverability.",
        outcome: "accepted",
      },
      {
        category: "proposal",
        summary:
          "Proposed a cross-team review cadence for prompt templates.",
        outcome: "accepted",
      },
    ],
    prsMerged: 5,
    prReviewsGiven: 10,
    afterHoursRatio: 0.04,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "alice@company.com",
    weekStart: "2025-11-24",
    pullRequestSummaries: [
      {
        type: "feature",
        area: "campaign analytics",
        impact: "core",
        summary: "Introduced cohort comparisons for campaign performance.",
        teamsAffected: ["marketing", "growth", "platform"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "fix",
        area: "image rendering",
        impact: "core",
        summary: "Fixed watermark alignment for social formats.",
        teamsAffected: ["marketing", "platform"],
        reviewFeedbackTone: "constructive",
        merged: true,
      },
      {
        type: "refactor",
        area: "prompt pipeline",
        impact: "core",
        summary: "Refined prompt scoring to reduce false negatives.",
        teamsAffected: ["growth", "platform"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "infra",
        area: "CI",
        impact: "edge",
        summary: "Added smoke tests for core render paths.",
        teamsAffected: ["infra", "platform"],
        reviewFeedbackTone: "minimal",
        merged: true,
      },
      {
        type: "feature",
        area: "API",
        impact: "core",
        summary: "Added bulk status endpoint for campaign coordination.",
        teamsAffected: ["platform", "marketing"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
    ],
    issueSummaries: [
      {
        category: "design discussion",
        summary:
          "Documented design guidelines for prompt templates across teams.",
        outcome: "accepted",
      },
      {
        category: "proposal",
        summary: "Suggested adding prompt template ownership metadata.",
        outcome: "accepted",
      },
    ],
    prsMerged: 5,
    prReviewsGiven: 11,
    afterHoursRatio: 0.04,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "alice@company.com",
    weekStart: "2025-12-01",
    pullRequestSummaries: [
      {
        type: "feature",
        area: "prompt pipeline",
        impact: "core",
        summary: "Enabled versioning for prompt templates to reduce regressions.",
        teamsAffected: ["platform", "growth", "marketing"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "fix",
        area: "render queue",
        impact: "core",
        summary: "Reduced retry storms by adding backoff jitter.",
        teamsAffected: ["platform", "infra"],
        reviewFeedbackTone: "constructive",
        merged: true,
      },
      {
        type: "refactor",
        area: "campaign analytics",
        impact: "core",
        summary: "Normalized analytics events for multi-channel campaigns.",
        teamsAffected: ["growth", "marketing"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "infra",
        area: "alerts",
        impact: "edge",
        summary: "Added alert routing for render SLA breaches.",
        teamsAffected: ["infra"],
        reviewFeedbackTone: "minimal",
        merged: true,
      },
      {
        type: "feature",
        area: "billing",
        impact: "core",
        summary: "Added cost previews for campaign variants.",
        teamsAffected: ["growth", "marketing"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
    ],
    issueSummaries: [
      {
        category: "design discussion",
        summary:
          "Led a review on how to surface prompt performance insights.",
        outcome: "accepted",
      },
      {
        category: "proposal",
        summary: "Proposed a prompt library governance workflow.",
        outcome: "accepted",
      },
    ],
    prsMerged: 5,
    prReviewsGiven: 12,
    afterHoursRatio: 0.05,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "alice@company.com",
    weekStart: "2025-12-08",
    pullRequestSummaries: [
      {
        type: "feature",
        area: "image rendering",
        impact: "core",
        summary: "Added adaptive quality settings for faster preview renders.",
        teamsAffected: ["platform", "marketing"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "fix",
        area: "API",
        impact: "core",
        summary: "Fixed race conditions in bulk render status polling.",
        teamsAffected: ["platform"],
        reviewFeedbackTone: "constructive",
        merged: true,
      },
      {
        type: "refactor",
        area: "prompt pipeline",
        impact: "core",
        summary: "Refined prompt caching to reduce latency on repeated runs.",
        teamsAffected: ["platform", "infra"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "feature",
        area: "campaign scheduler",
        impact: "core",
        summary: "Added fallback windows for delayed launches.",
        teamsAffected: ["marketing", "growth"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "infra",
        area: "observability",
        impact: "edge",
        summary: "Expanded tracing across prompt version rollouts.",
        teamsAffected: ["infra"],
        reviewFeedbackTone: "minimal",
        merged: true,
      },
    ],
    issueSummaries: [
      {
        category: "design discussion",
        summary: "Opened a thread on harmonizing campaign naming conventions.",
        outcome: "accepted",
      },
      {
        category: "bug",
        summary: "Flagged intermittent lag in the prompt library search.",
        outcome: "accepted",
      },
    ],
    prsMerged: 5,
    prReviewsGiven: 12,
    afterHoursRatio: 0.05,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "alice@company.com",
    weekStart: "2025-12-15",
    pullRequestSummaries: [
      {
        type: "feature",
        area: "campaign analytics",
        impact: "core",
        summary:
          "Added cross-campaign performance rollups for quarterly reviews.",
        teamsAffected: ["marketing", "growth", "platform"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "fix",
        area: "render orchestration",
        impact: "core",
        summary: "Fixed retry accounting to prevent duplicate billing.",
        teamsAffected: ["platform", "growth"],
        reviewFeedbackTone: "constructive",
        merged: true,
      },
      {
        type: "refactor",
        area: "API",
        impact: "core",
        summary: "Refactored request validation for prompt template updates.",
        teamsAffected: ["platform"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "feature",
        area: "prompt pipeline",
        impact: "core",
        summary: "Added prompt linting checks to reduce invalid submissions.",
        teamsAffected: ["platform", "marketing"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "infra",
        area: "CI",
        impact: "edge",
        summary: "Added load test target for render bursts.",
        teamsAffected: ["infra"],
        reviewFeedbackTone: "minimal",
        merged: true,
      },
    ],
    issueSummaries: [
      {
        category: "design discussion",
        summary: "Summarized learnings from prompt template adoption.",
        outcome: "accepted",
      },
      {
        category: "proposal",
        summary: "Proposed a shared review board for prompt changes.",
        outcome: "accepted",
      },
    ],
    prsMerged: 5,
    prReviewsGiven: 13,
    afterHoursRatio: 0.04,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "alice@company.com",
    weekStart: "2025-12-22",
    pullRequestSummaries: [
      {
        type: "feature",
        area: "prompt pipeline",
        impact: "core",
        summary: "Shipped prompt template inheritance for brand families.",
        teamsAffected: ["marketing", "growth", "platform"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "feature",
        area: "campaign analytics",
        impact: "core",
        summary:
          "Added year-end performance snapshots for leadership reviews.",
        teamsAffected: ["marketing", "growth"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "fix",
        area: "image rendering",
        impact: "core",
        summary: "Fixed rendering artifacts in large batch campaigns.",
        teamsAffected: ["platform", "marketing"],
        reviewFeedbackTone: "constructive",
        merged: true,
      },
      {
        type: "refactor",
        area: "render orchestration",
        impact: "core",
        summary: "Consolidated render job routing for simpler support.",
        teamsAffected: ["platform", "infra"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "infra",
        area: "observability",
        impact: "edge",
        summary: "Added dashboards for prompt version drift.",
        teamsAffected: ["infra"],
        reviewFeedbackTone: "minimal",
        merged: true,
      },
      {
        type: "feature",
        area: "billing",
        impact: "core",
        summary: "Added multi-currency support for enterprise trials.",
        teamsAffected: ["growth", "platform"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
    ],
    issueSummaries: [
      {
        category: "design discussion",
        summary:
          "Facilitated a post-mortem on campaign performance insights.",
        outcome: "accepted",
      },
      {
        category: "proposal",
        summary: "Proposed a roadmap for prompt personalization.",
        outcome: "accepted",
      },
    ],
    prsMerged: 6,
    prReviewsGiven: 14,
    afterHoursRatio: 0.04,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "bob@company.com",
    weekStart: "2025-10-06",
    pullRequestSummaries: [
      {
        type: "feature",
        area: "image rendering",
        impact: "core",
        summary: "Implemented new render queue prioritization for launch week.",
        teamsAffected: ["platform", "infra", "marketing"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "fix",
        area: "API",
        impact: "core",
        summary: "Fixed payload validation for bulk generation.",
        teamsAffected: ["platform"],
        reviewFeedbackTone: "constructive",
        merged: true,
      },
      {
        type: "feature",
        area: "billing",
        impact: "core",
        summary: "Added usage caps to prevent runaway spend.",
        teamsAffected: ["growth", "platform"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "refactor",
        area: "render orchestration",
        impact: "core",
        summary: "Refactored job retries to reduce latency spikes.",
        teamsAffected: ["platform", "infra"],
        reviewFeedbackTone: "constructive",
        merged: true,
      },
      {
        type: "infra",
        area: "alerts",
        impact: "edge",
        summary: "Added on-call alerts for render failures.",
        teamsAffected: ["infra"],
        reviewFeedbackTone: "minimal",
        merged: false,
      },
    ],
    issueSummaries: [
      {
        category: "bug",
        summary: "Filed a bug for intermittent API timeouts during peak load.",
        outcome: "accepted",
      },
    ],
    prsMerged: 4,
    prReviewsGiven: 6,
    afterHoursRatio: 0.24,
    weekendRatio: 0.1,
  },
  {
    employeeEmail: "bob@company.com",
    weekStart: "2025-10-13",
    pullRequestSummaries: [
      {
        type: "feature",
        area: "image rendering",
        impact: "core",
        summary: "Added caching for frequently requested render presets.",
        teamsAffected: ["platform", "infra"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "fix",
        area: "render queue",
        impact: "core",
        summary: "Fixed job ordering when priorities are updated.",
        teamsAffected: ["platform"],
        reviewFeedbackTone: "constructive",
        merged: true,
      },
      {
        type: "feature",
        area: "campaign scheduler",
        impact: "core",
        summary: "Enabled emergency campaign reschedules.",
        teamsAffected: ["marketing", "growth"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "refactor",
        area: "API",
        impact: "core",
        summary: "Refactored batch endpoints to reduce payload size.",
        teamsAffected: ["platform"],
        reviewFeedbackTone: "constructive",
        merged: true,
      },
    ],
    issueSummaries: [
      {
        category: "proposal",
        summary: "Suggested a higher default concurrency for render workers.",
        outcome: "accepted",
      },
    ],
    prsMerged: 4,
    prReviewsGiven: 7,
    afterHoursRatio: 0.28,
    weekendRatio: 0.12,
  },
  {
    employeeEmail: "bob@company.com",
    weekStart: "2025-10-20",
    pullRequestSummaries: [
      {
        type: "feature",
        area: "render orchestration",
        impact: "core",
        summary: "Added burst capacity for high-volume campaigns.",
        teamsAffected: ["platform", "infra", "marketing"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "fix",
        area: "billing",
        impact: "core",
        summary: "Fixed invoice reconciliation for enterprise trials.",
        teamsAffected: ["growth"],
        reviewFeedbackTone: "constructive",
        merged: true,
      },
      {
        type: "feature",
        area: "API",
        impact: "core",
        summary: "Added bulk cancel endpoint for stalled renders.",
        teamsAffected: ["platform"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "refactor",
        area: "image rendering",
        impact: "core",
        summary: "Consolidated render presets to reduce duplication.",
        teamsAffected: ["platform"],
        reviewFeedbackTone: "constructive",
        merged: true,
      },
      {
        type: "infra",
        area: "metrics",
        impact: "edge",
        summary: "Added dashboards for queue saturation.",
        teamsAffected: ["infra"],
        reviewFeedbackTone: "minimal",
        merged: false,
      },
    ],
    issueSummaries: [
      {
        category: "bug",
        summary: "Logged a defect on render retries causing double counts.",
        outcome: "accepted",
      },
      {
        category: "tech debt",
        summary: "Proposed cleanup for legacy render workers.",
        outcome: "accepted",
      },
    ],
    prsMerged: 4,
    prReviewsGiven: 8,
    afterHoursRatio: 0.32,
    weekendRatio: 0.15,
  },
  {
    employeeEmail: "bob@company.com",
    weekStart: "2025-10-27",
    pullRequestSummaries: [
      {
        type: "feature",
        area: "image rendering",
        impact: "core",
        summary: "Added faster render path for standard ad sizes.",
        teamsAffected: ["platform", "marketing"],
        reviewFeedbackTone: "constructive",
        merged: true,
      },
      {
        type: "fix",
        area: "render queue",
        impact: "core",
        summary: "Fixed stalled jobs when workers recycle.",
        teamsAffected: ["platform", "infra"],
        reviewFeedbackTone: "constructive",
        merged: true,
      },
      {
        type: "refactor",
        area: "API",
        impact: "core",
        summary: "Refactored job status polling to reduce load.",
        teamsAffected: ["platform"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
      {
        type: "infra",
        area: "alerts",
        impact: "edge",
        summary: "Added aggressive alert thresholds for launch week stability.",
        teamsAffected: ["infra"],
        reviewFeedbackTone: "minimal",
        merged: true,
      },
    ],
    issueSummaries: [
      {
        category: "bug",
        summary: "Reported priority inversion during heavy queue use.",
        outcome: "accepted",
      },
    ],
    prsMerged: 4,
    prReviewsGiven: 9,
    afterHoursRatio: 0.35,
    weekendRatio: 0.18,
  },
  {
    employeeEmail: "bob@company.com",
    weekStart: "2025-11-03",
    pullRequestSummaries: [
      {
        type: "fix",
        area: "image rendering",
        impact: "core",
        summary: "Patched render failure handling for large batch jobs.",
        teamsAffected: ["platform", "infra"],
        reviewFeedbackTone: "constructive",
        merged: true,
      },
      {
        type: "fix",
        area: "API",
        impact: "core",
        summary: "Fixed intermittent 500s on batch endpoints.",
        teamsAffected: ["platform"],
        reviewFeedbackTone: "minimal",
        merged: true,
      },
      {
        type: "refactor",
        area: "render orchestration",
        impact: "core",
        summary: "Reduced retry storms by tightening backoff defaults.",
        teamsAffected: ["platform", "infra"],
        reviewFeedbackTone: "constructive",
        merged: true,
      },
      {
        type: "infra",
        area: "metrics",
        impact: "edge",
        summary: "Added short-term dashboards for incident triage.",
        teamsAffected: ["infra"],
        reviewFeedbackTone: "minimal",
        merged: false,
      },
    ],
    issueSummaries: [
      {
        category: "bug",
        summary: "Opened an incident report on render timeouts under load.",
        outcome: "accepted",
      },
    ],
    prsMerged: 3,
    prReviewsGiven: 7,
    afterHoursRatio: 0.4,
    weekendRatio: 0.22,
  },
  {
    employeeEmail: "bob@company.com",
    weekStart: "2025-11-10",
    pullRequestSummaries: [
      {
        type: "fix",
        area: "render queue",
        impact: "core",
        summary:
          "Hotfixed queue lag by increasing worker heartbeat tolerance.",
        teamsAffected: ["platform", "infra"],
        reviewFeedbackTone: "minimal",
        merged: true,
      },
      {
        type: "fix",
        area: "billing",
        impact: "core",
        summary: "Fixed delayed usage sync after worker restarts.",
        teamsAffected: ["growth"],
        reviewFeedbackTone: "minimal",
        merged: true,
      },
      {
        type: "infra",
        area: "alerts",
        impact: "edge",
        summary: "Adjusted alert noise thresholds after incidents.",
        teamsAffected: ["infra"],
        reviewFeedbackTone: "minimal",
        merged: false,
      },
    ],
    issueSummaries: [
      {
        category: "tech debt",
        summary: "Raised concern about operational overhead in render workers.",
        outcome: "deferred",
      },
    ],
    prsMerged: 2,
    prReviewsGiven: 5,
    afterHoursRatio: 0.45,
    weekendRatio: 0.28,
  },
  {
    employeeEmail: "bob@company.com",
    weekStart: "2025-11-17",
    pullRequestSummaries: [
      {
        type: "fix",
        area: "image rendering",
        impact: "core",
        summary: "Applied urgent fix for render retries doubling billing.",
        teamsAffected: ["platform", "growth"],
        reviewFeedbackTone: "minimal",
        merged: true,
      },
      {
        type: "fix",
        area: "API",
        impact: "core",
        summary: "Patched response serialization to avoid timeouts.",
        teamsAffected: ["platform"],
        reviewFeedbackTone: "minimal",
        merged: false,
      },
      {
        type: "infra",
        area: "metrics",
        impact: "edge",
        summary: "Added temporary logging for queue stalls.",
        teamsAffected: ["infra"],
        reviewFeedbackTone: "minimal",
        merged: false,
      },
    ],
    issueSummaries: [
      {
        category: "bug",
        summary: "Documented recurring queue stalls tied to high concurrency.",
        outcome: "accepted",
      },
    ],
    prsMerged: 1,
    prReviewsGiven: 4,
    afterHoursRatio: 0.5,
    weekendRatio: 0.32,
  },
  {
    employeeEmail: "bob@company.com",
    weekStart: "2025-11-24",
    pullRequestSummaries: [
      {
        type: "fix",
        area: "render orchestration",
        impact: "core",
        summary: "Applied emergency tweak to reduce failed retry loops.",
        teamsAffected: ["platform", "infra"],
        reviewFeedbackTone: "minimal",
        merged: true,
      },
      {
        type: "fix",
        area: "billing",
        impact: "core",
        summary: "Patched billing reconciliation for partial renders.",
        teamsAffected: ["growth"],
        reviewFeedbackTone: "minimal",
        merged: false,
      },
    ],
    issueSummaries: [
      {
        category: "bug",
        summary: "Raised a blocker about recurring render backlogs.",
        outcome: "accepted",
      },
    ],
    prsMerged: 1,
    prReviewsGiven: 3,
    afterHoursRatio: 0.55,
    weekendRatio: 0.4,
  },
  {
    employeeEmail: "bob@company.com",
    weekStart: "2025-12-01",
    pullRequestSummaries: [
      {
        type: "fix",
        area: "image rendering",
        impact: "core",
        summary:
          "Applied a targeted fix for output corruption in large batches.",
        teamsAffected: ["platform", "marketing"],
        reviewFeedbackTone: "minimal",
        merged: true,
      },
      {
        type: "infra",
        area: "alerts",
        impact: "edge",
        summary: "Added temporary alerts for weekend incident coverage.",
        teamsAffected: ["infra"],
        reviewFeedbackTone: "minimal",
        merged: false,
      },
    ],
    issueSummaries: [
      {
        category: "bug",
        summary: "Noted a continuing backlog in render processing.",
        outcome: "deferred",
      },
    ],
    prsMerged: 1,
    prReviewsGiven: 2,
    afterHoursRatio: 0.6,
    weekendRatio: 0.45,
  },
  {
    employeeEmail: "bob@company.com",
    weekStart: "2025-12-08",
    pullRequestSummaries: [
      {
        type: "fix",
        area: "API",
        impact: "core",
        summary: "Patched timeout handling for bulk status requests.",
        teamsAffected: ["platform"],
        reviewFeedbackTone: "minimal",
        merged: true,
      },
      {
        type: "infra",
        area: "metrics",
        impact: "edge",
        summary: "Added minimal metrics to track backlog size.",
        teamsAffected: ["infra"],
        reviewFeedbackTone: "minimal",
        merged: false,
      },
    ],
    issueSummaries: [],
    prsMerged: 1,
    prReviewsGiven: 2,
    afterHoursRatio: 0.58,
    weekendRatio: 0.42,
  },
  {
    employeeEmail: "bob@company.com",
    weekStart: "2025-12-15",
    pullRequestSummaries: [
      {
        type: "fix",
        area: "render queue",
        impact: "core",
        summary: "Applied a small tweak to reduce stuck jobs.",
        teamsAffected: ["platform"],
        reviewFeedbackTone: "minimal",
        merged: false,
      },
      {
        type: "infra",
        area: "alerts",
        impact: "edge",
        summary: "Reduced alerting scope to essential errors.",
        teamsAffected: ["infra"],
        reviewFeedbackTone: "minimal",
        merged: false,
      },
    ],
    issueSummaries: [
      {
        category: "tech debt",
        summary: "Flagged need for a broader queue redesign.",
        outcome: "deferred",
      },
    ],
    prsMerged: 0,
    prReviewsGiven: 1,
    afterHoursRatio: 0.6,
    weekendRatio: 0.5,
  },
  {
    employeeEmail: "bob@company.com",
    weekStart: "2025-12-22",
    pullRequestSummaries: [
      {
        type: "fix",
        area: "billing",
        impact: "core",
        summary: "Patched invoice summaries for delayed usage updates.",
        teamsAffected: ["growth"],
        reviewFeedbackTone: "minimal",
        merged: false,
      },
      {
        type: "infra",
        area: "metrics",
        impact: "edge",
        summary: "Added a temporary counter for failed renders.",
        teamsAffected: ["infra"],
        reviewFeedbackTone: "minimal",
        merged: false,
      },
    ],
    issueSummaries: [],
    prsMerged: 0,
    prReviewsGiven: 0,
    afterHoursRatio: 0.62,
    weekendRatio: 0.52,
  },
  {
    employeeEmail: "carol@company.com",
    weekStart: "2025-10-06",
    pullRequestSummaries: [
      {
        type: "fix",
        area: "UI",
        impact: "edge",
        summary: "Adjusted minor UI spacing in campaign list.",
        teamsAffected: ["marketing"],
        reviewFeedbackTone: "minimal",
        merged: true,
      },
    ],
    issueSummaries: [],
    prsMerged: 1,
    prReviewsGiven: 0,
    afterHoursRatio: 0.01,
    weekendRatio: 0.0,
  },
  {
    employeeEmail: "carol@company.com",
    weekStart: "2025-10-13",
    pullRequestSummaries: [
      {
        type: "fix",
        area: "API",
        impact: "edge",
        summary: "Fixed a typo in a response field name.",
        teamsAffected: ["platform"],
        reviewFeedbackTone: "minimal",
        merged: true,
      },
    ],
    issueSummaries: [],
    prsMerged: 1,
    prReviewsGiven: 0,
    afterHoursRatio: 0.0,
    weekendRatio: 0.0,
  },
  {
    employeeEmail: "carol@company.com",
    weekStart: "2025-10-20",
    pullRequestSummaries: [
      {
        type: "fix",
        area: "UI",
        impact: "edge",
        summary: "Updated empty state text for campaign drafts.",
        teamsAffected: ["marketing"],
        reviewFeedbackTone: "minimal",
        merged: false,
      },
    ],
    issueSummaries: [],
    prsMerged: 0,
    prReviewsGiven: 0,
    afterHoursRatio: 0.0,
    weekendRatio: 0.0,
  },
  {
    employeeEmail: "carol@company.com",
    weekStart: "2025-10-27",
    pullRequestSummaries: [
      {
        type: "fix",
        area: "UI",
        impact: "edge",
        summary: "Fixed button alignment on the campaign details page.",
        teamsAffected: ["marketing"],
        reviewFeedbackTone: "minimal",
        merged: true,
      },
    ],
    issueSummaries: [],
    prsMerged: 1,
    prReviewsGiven: 0,
    afterHoursRatio: 0.02,
    weekendRatio: 0.0,
  },
  {
    employeeEmail: "carol@company.com",
    weekStart: "2025-11-03",
    pullRequestSummaries: [
      {
        type: "fix",
        area: "API",
        impact: "edge",
        summary: "Adjusted logging to reduce noise in staging.",
        teamsAffected: ["infra"],
        reviewFeedbackTone: "minimal",
        merged: true,
      },
      {
        type: "fix",
        area: "UI",
        impact: "edge",
        summary: "Corrected label casing in campaign filters.",
        teamsAffected: ["marketing"],
        reviewFeedbackTone: "minimal",
        merged: false,
      },
    ],
    issueSummaries: [
      {
        category: "bug",
        summary: "Noted a minor label mismatch in the filters panel.",
        outcome: "deferred",
      },
    ],
    prsMerged: 1,
    prReviewsGiven: 0,
    afterHoursRatio: 0.01,
    weekendRatio: 0.0,
  },
  {
    employeeEmail: "carol@company.com",
    weekStart: "2025-11-10",
    pullRequestSummaries: [
      {
        type: "fix",
        area: "UI",
        impact: "edge",
        summary: "Updated placeholder text for prompt templates.",
        teamsAffected: ["marketing"],
        reviewFeedbackTone: "minimal",
        merged: false,
      },
    ],
    issueSummaries: [],
    prsMerged: 0,
    prReviewsGiven: 0,
    afterHoursRatio: 0.0,
    weekendRatio: 0.0,
  },
  {
    employeeEmail: "carol@company.com",
    weekStart: "2025-11-17",
    pullRequestSummaries: [
      {
        type: "fix",
        area: "UI",
        impact: "edge",
        summary: "Removed outdated tooltip copy from settings.",
        teamsAffected: ["marketing"],
        reviewFeedbackTone: "minimal",
        merged: false,
      },
    ],
    issueSummaries: [],
    prsMerged: 0,
    prReviewsGiven: 0,
    afterHoursRatio: 0.0,
    weekendRatio: 0.0,
  },
  {
    employeeEmail: "carol@company.com",
    weekStart: "2025-11-24",
    pullRequestSummaries: [
      {
        type: "fix",
        area: "API",
        impact: "edge",
        summary: "Adjusted a small response field ordering issue.",
        teamsAffected: ["platform"],
        reviewFeedbackTone: "minimal",
        merged: true,
      },
    ],
    issueSummaries: [],
    prsMerged: 1,
    prReviewsGiven: 0,
    afterHoursRatio: 0.01,
    weekendRatio: 0.0,
  },
  {
    employeeEmail: "carol@company.com",
    weekStart: "2025-12-01",
    pullRequestSummaries: [
      {
        type: "fix",
        area: "UI",
        impact: "edge",
        summary: "Fixed minor spacing in the prompt library list.",
        teamsAffected: ["marketing"],
        reviewFeedbackTone: "minimal",
        merged: true,
      },
    ],
    issueSummaries: [],
    prsMerged: 1,
    prReviewsGiven: 0,
    afterHoursRatio: 0.0,
    weekendRatio: 0.0,
  },
  {
    employeeEmail: "carol@company.com",
    weekStart: "2025-12-08",
    pullRequestSummaries: [
      {
        type: "fix",
        area: "UI",
        impact: "edge",
        summary: "Updated empty state copy for the prompt library.",
        teamsAffected: ["marketing"],
        reviewFeedbackTone: "minimal",
        merged: false,
      },
    ],
    issueSummaries: [],
    prsMerged: 0,
    prReviewsGiven: 0,
    afterHoursRatio: 0.0,
    weekendRatio: 0.0,
  },
  {
    employeeEmail: "carol@company.com",
    weekStart: "2025-12-15",
    pullRequestSummaries: [
      {
        type: "fix",
        area: "API",
        impact: "edge",
        summary: "Removed a deprecated response field.",
        teamsAffected: ["platform"],
        reviewFeedbackTone: "minimal",
        merged: false,
      },
    ],
    issueSummaries: [],
    prsMerged: 0,
    prReviewsGiven: 0,
    afterHoursRatio: 0.0,
    weekendRatio: 0.0,
  },
  {
    employeeEmail: "carol@company.com",
    weekStart: "2025-12-22",
    pullRequestSummaries: [
      {
        type: "fix",
        area: "UI",
        impact: "edge",
        summary: "Corrected a small label typo in settings.",
        teamsAffected: ["marketing"],
        reviewFeedbackTone: "minimal",
        merged: false,
      },
    ],
    issueSummaries: [],
    prsMerged: 0,
    prReviewsGiven: 0,
    afterHoursRatio: 0.0,
    weekendRatio: 0.0,
  },
  {
    employeeEmail: "dave@company.com",
    weekStart: "2025-10-06",
    pullRequestSummaries: [
      {
        type: "fix",
        area: "UI",
        impact: "edge",
        summary: "Adjusted spacing in campaign cards for visual consistency.",
        teamsAffected: ["marketing"],
        reviewFeedbackTone: "minimal",
        merged: true,
      },
    ],
    issueSummaries: [],
    prsMerged: 1,
    prReviewsGiven: 0,
    afterHoursRatio: 0.05,
    weekendRatio: 0.02,
  },
  {
    employeeEmail: "dave@company.com",
    weekStart: "2025-10-13",
    pullRequestSummaries: [],
    issueSummaries: [],
    prsMerged: 0,
    prReviewsGiven: 0,
    afterHoursRatio: 0.06,
    weekendRatio: 0.02,
  },
  {
    employeeEmail: "dave@company.com",
    weekStart: "2025-10-20",
    pullRequestSummaries: [
      {
        type: "fix",
        area: "copy",
        impact: "edge",
        summary: "Updated tooltip wording for campaign filters.",
        teamsAffected: ["marketing"],
        reviewFeedbackTone: "minimal",
        merged: true,
      },
    ],
    issueSummaries: [],
    prsMerged: 1,
    prReviewsGiven: 0,
    afterHoursRatio: 0.07,
    weekendRatio: 0.02,
  },
  {
    employeeEmail: "dave@company.com",
    weekStart: "2025-10-27",
    pullRequestSummaries: [],
    issueSummaries: [],
    prsMerged: 0,
    prReviewsGiven: 0,
    afterHoursRatio: 0.06,
    weekendRatio: 0.03,
  },
  {
    employeeEmail: "dave@company.com",
    weekStart: "2025-11-03",
    pullRequestSummaries: [
      {
        type: "fix",
        area: "UI",
        impact: "edge",
        summary: "Adjusted button alignment in campaign sidebar.",
        teamsAffected: ["marketing"],
        reviewFeedbackTone: "minimal",
        merged: true,
      },
    ],
    issueSummaries: [],
    prsMerged: 1,
    prReviewsGiven: 0,
    afterHoursRatio: 0.06,
    weekendRatio: 0.02,
  },
  {
    employeeEmail: "dave@company.com",
    weekStart: "2025-11-10",
    pullRequestSummaries: [],
    issueSummaries: [],
    prsMerged: 0,
    prReviewsGiven: 0,
    afterHoursRatio: 0.07,
    weekendRatio: 0.03,
  },
  {
    employeeEmail: "dave@company.com",
    weekStart: "2025-11-17",
    pullRequestSummaries: [
      {
        type: "fix",
        area: "UI",
        impact: "edge",
        summary: "Updated empty state illustration spacing.",
        teamsAffected: ["marketing"],
        reviewFeedbackTone: "minimal",
        merged: false,
      },
    ],
    issueSummaries: [],
    prsMerged: 0,
    prReviewsGiven: 0,
    afterHoursRatio: 0.08,
    weekendRatio: 0.03,
  },
  {
    employeeEmail: "dave@company.com",
    weekStart: "2025-11-24",
    pullRequestSummaries: [],
    issueSummaries: [],
    prsMerged: 0,
    prReviewsGiven: 0,
    afterHoursRatio: 0.07,
    weekendRatio: 0.03,
  },
  {
    employeeEmail: "dave@company.com",
    weekStart: "2025-12-01",
    pullRequestSummaries: [
      {
        type: "fix",
        area: "copy",
        impact: "edge",
        summary: "Changed placeholder text in prompt input.",
        teamsAffected: ["marketing"],
        reviewFeedbackTone: "minimal",
        merged: true,
      },
    ],
    issueSummaries: [],
    prsMerged: 1,
    prReviewsGiven: 0,
    afterHoursRatio: 0.06,
    weekendRatio: 0.02,
  },
  {
    employeeEmail: "dave@company.com",
    weekStart: "2025-12-08",
    pullRequestSummaries: [],
    issueSummaries: [],
    prsMerged: 0,
    prReviewsGiven: 0,
    afterHoursRatio: 0.07,
    weekendRatio: 0.03,
  },
  {
    employeeEmail: "dave@company.com",
    weekStart: "2025-12-15",
    pullRequestSummaries: [],
    issueSummaries: [],
    prsMerged: 0,
    prReviewsGiven: 0,
    afterHoursRatio: 0.08,
    weekendRatio: 0.04,
  },
  {
    employeeEmail: "dave@company.com",
    weekStart: "2025-12-22",
    pullRequestSummaries: [],
    issueSummaries: [],
    prsMerged: 0,
    prReviewsGiven: 0,
    afterHoursRatio: 0.07,
    weekendRatio: 0.04,
  },
  {
    employeeEmail: "eve@company.com",
    weekStart: "2025-10-06",
    pullRequestSummaries: [
      {
        type: "refactor",
        area: "render orchestration",
        impact: "core",
        summary:
          "Simplified render job state transitions to reduce edge-case failures.",
        teamsAffected: ["platform", "infra"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
    ],
    issueSummaries: [],
    prsMerged: 1,
    prReviewsGiven: 2,
    afterHoursRatio: 0.03,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "eve@company.com",
    weekStart: "2025-10-13",
    pullRequestSummaries: [
      {
        type: "feature",
        area: "prompt pipeline",
        impact: "core",
        summary:
          "Introduced deterministic prompt normalization to reduce variance.",
        teamsAffected: ["platform", "growth"],
        reviewFeedbackTone: "constructive",
        merged: true,
      },
    ],
    issueSummaries: [],
    prsMerged: 1,
    prReviewsGiven: 3,
    afterHoursRatio: 0.03,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "eve@company.com",
    weekStart: "2025-10-20",
    pullRequestSummaries: [
      {
        type: "refactor",
        area: "image rendering",
        impact: "core",
        summary:
          "Reduced rendering hot paths by consolidating shared transforms.",
        teamsAffected: ["platform"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
    ],
    issueSummaries: [
      {
        category: "tech debt",
        summary: "Identified redundant render paths impacting latency.",
        outcome: "accepted",
      },
    ],
    prsMerged: 1,
    prReviewsGiven: 3,
    afterHoursRatio: 0.02,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "eve@company.com",
    weekStart: "2025-10-27",
    pullRequestSummaries: [
      {
        type: "feature",
        area: "campaign analytics",
        impact: "core",
        summary:
          "Added canonical campaign identifiers to stabilize analytics joins.",
        teamsAffected: ["growth", "marketing"],
        reviewFeedbackTone: "constructive",
        merged: true,
      },
    ],
    issueSummaries: [],
    prsMerged: 1,
    prReviewsGiven: 4,
    afterHoursRatio: 0.03,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "eve@company.com",
    weekStart: "2025-11-03",
    pullRequestSummaries: [
      {
        type: "infra",
        area: "metrics",
        impact: "core",
        summary: "Added low-level latency histograms for render stages.",
        teamsAffected: ["infra", "platform"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
    ],
    issueSummaries: [],
    prsMerged: 1,
    prReviewsGiven: 4,
    afterHoursRatio: 0.02,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "eve@company.com",
    weekStart: "2025-11-10",
    pullRequestSummaries: [
      {
        type: "refactor",
        area: "API",
        impact: "core",
        summary: "Simplified request validation to reduce failure modes.",
        teamsAffected: ["platform"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
    ],
    issueSummaries: [],
    prsMerged: 1,
    prReviewsGiven: 5,
    afterHoursRatio: 0.03,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "eve@company.com",
    weekStart: "2025-11-17",
    pullRequestSummaries: [
      {
        type: "feature",
        area: "render orchestration",
        impact: "core",
        summary: "Enabled graceful degradation for overloaded render queues.",
        teamsAffected: ["platform", "infra"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
    ],
    issueSummaries: [
      {
        category: "proposal",
        summary: "Suggested queue fairness improvements based on observed load.",
        outcome: "accepted",
      },
    ],
    prsMerged: 1,
    prReviewsGiven: 5,
    afterHoursRatio: 0.03,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "eve@company.com",
    weekStart: "2025-11-24",
    pullRequestSummaries: [
      {
        type: "refactor",
        area: "prompt pipeline",
        impact: "core",
        summary: "Reduced prompt execution branching for maintainability.",
        teamsAffected: ["platform"],
        reviewFeedbackTone: "constructive",
        merged: true,
      },
    ],
    issueSummaries: [],
    prsMerged: 1,
    prReviewsGiven: 6,
    afterHoursRatio: 0.02,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "eve@company.com",
    weekStart: "2025-12-01",
    pullRequestSummaries: [
      {
        type: "feature",
        area: "image rendering",
        impact: "core",
        summary:
          "Introduced a safer fallback path for experimental render modes.",
        teamsAffected: ["platform"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
    ],
    issueSummaries: [],
    prsMerged: 1,
    prReviewsGiven: 6,
    afterHoursRatio: 0.02,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "eve@company.com",
    weekStart: "2025-12-08",
    pullRequestSummaries: [
      {
        type: "infra",
        area: "observability",
        impact: "core",
        summary: "Added targeted tracing for rare render failures.",
        teamsAffected: ["infra"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
    ],
    issueSummaries: [],
    prsMerged: 1,
    prReviewsGiven: 6,
    afterHoursRatio: 0.02,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "eve@company.com",
    weekStart: "2025-12-15",
    pullRequestSummaries: [
      {
        type: "refactor",
        area: "campaign analytics",
        impact: "core",
        summary:
          "Normalized analytics joins to reduce downstream inconsistencies.",
        teamsAffected: ["growth", "marketing"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
    ],
    issueSummaries: [],
    prsMerged: 1,
    prReviewsGiven: 7,
    afterHoursRatio: 0.02,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "eve@company.com",
    weekStart: "2025-12-22",
    pullRequestSummaries: [
      {
        type: "feature",
        area: "prompt pipeline",
        impact: "core",
        summary: "Added guardrails to prevent invalid prompt inheritance.",
        teamsAffected: ["platform", "growth"],
        reviewFeedbackTone: "positive",
        merged: true,
      },
    ],
    issueSummaries: [],
    prsMerged: 1,
    prReviewsGiven: 7,
    afterHoursRatio: 0.02,
    weekendRatio: 0.01,
  },
];

export const slackWeeklyData: SlackWeekRow[] = [
  {
    employeeEmail: "alice@company.com",
    weekStart: "2025-10-06",
    messageSummaries: [
      {
        theme: "launch coordination",
        intent: "collaboration",
        sentiment: "positive",
        example:
          "Coordinated launch checklist updates across platform and marketing.",
      },
      {
        theme: "bug triage",
        intent: "support",
        sentiment: "neutral",
        example: "Helped triage a render timeout report and suggested next steps.",
      },
      {
        theme: "prompt alignment",
        intent: "collaboration",
        sentiment: "positive",
        example: "Aligned on prompt template updates for a holiday campaign.",
      },
    ],
    messageCount: 52,
    replyCount: 34,
    reactionsReceived: 26,
    afterHoursRatio: 0.04,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "alice@company.com",
    weekStart: "2025-10-13",
    messageSummaries: [
      {
        theme: "launch coordination",
        intent: "collaboration",
        sentiment: "positive",
        example: "Synced campaign timing with growth and marketing stakeholders.",
      },
      {
        theme: "support",
        intent: "support",
        sentiment: "positive",
        example:
          "Provided guidance on prompt template reuse for new variants.",
      },
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Posted a concise update on render queue improvements.",
      },
      {
        theme: "blocker discussion",
        intent: "collaboration",
        sentiment: "neutral",
        example: "Worked with infra to unblock a deployment check.",
      },
    ],
    messageCount: 56,
    replyCount: 37,
    reactionsReceived: 28,
    afterHoursRatio: 0.04,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "alice@company.com",
    weekStart: "2025-10-20",
    messageSummaries: [
      {
        theme: "alignment",
        intent: "collaboration",
        sentiment: "positive",
        example: "Aligned on prompt scoring changes for growth experiments.",
      },
      {
        theme: "support",
        intent: "support",
        sentiment: "positive",
        example: "Answered questions about batch export behavior.",
      },
      {
        theme: "bug triage",
        intent: "support",
        sentiment: "neutral",
        example: "Shared a workaround for an intermittent cache issue.",
      },
    ],
    messageCount: 55,
    replyCount: 36,
    reactionsReceived: 29,
    afterHoursRatio: 0.03,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "alice@company.com",
    weekStart: "2025-10-27",
    messageSummaries: [
      {
        theme: "launch coordination",
        intent: "collaboration",
        sentiment: "positive",
        example: "Coordinated cross-team rollout steps for new render presets.",
      },
      {
        theme: "support",
        intent: "support",
        sentiment: "positive",
        example: "Helped marketing validate campaign preview outputs.",
      },
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Posted progress on prompt template rollout.",
      },
      {
        theme: "alignment",
        intent: "collaboration",
        sentiment: "positive",
        example: "Aligned on analytics metrics for campaign reporting.",
      },
    ],
    messageCount: 60,
    replyCount: 40,
    reactionsReceived: 32,
    afterHoursRatio: 0.03,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "alice@company.com",
    weekStart: "2025-11-03",
    messageSummaries: [
      {
        theme: "design discussion",
        intent: "collaboration",
        sentiment: "positive",
        example: "Led a design thread on prompt template discoverability.",
      },
      {
        theme: "support",
        intent: "support",
        sentiment: "positive",
        example: "Helped growth team troubleshoot template adoption issues.",
      },
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Shared updates on render queue fixes.",
      },
      {
        theme: "launch coordination",
        intent: "collaboration",
        sentiment: "positive",
        example: "Coordinated analytics changes for marketing launches.",
      },
    ],
    messageCount: 62,
    replyCount: 42,
    reactionsReceived: 35,
    afterHoursRatio: 0.03,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "alice@company.com",
    weekStart: "2025-11-10",
    messageSummaries: [
      {
        theme: "design discussion",
        intent: "collaboration",
        sentiment: "positive",
        example: "Aligned stakeholders on prompt governance changes.",
      },
      {
        theme: "support",
        intent: "support",
        sentiment: "positive",
        example: "Helped debug a campaign analytics discrepancy.",
      },
      {
        theme: "alignment",
        intent: "collaboration",
        sentiment: "positive",
        example: "Synced priorities with infra on render observability.",
      },
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Posted a weekly summary of platform improvements.",
      },
    ],
    messageCount: 66,
    replyCount: 45,
    reactionsReceived: 38,
    afterHoursRatio: 0.04,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "alice@company.com",
    weekStart: "2025-11-17",
    messageSummaries: [
      {
        theme: "alignment",
        intent: "collaboration",
        sentiment: "positive",
        example:
          "Aligned cross-team priorities for render orchestration changes.",
      },
      {
        theme: "support",
        intent: "support",
        sentiment: "positive",
        example: "Unblocked marketing with guidance on template versioning.",
      },
      {
        theme: "design discussion",
        intent: "collaboration",
        sentiment: "positive",
        example:
          "Captured feedback on analytics rollups and sharing cadence.",
      },
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Shared progress on render priority controls.",
      },
    ],
    messageCount: 68,
    replyCount: 47,
    reactionsReceived: 40,
    afterHoursRatio: 0.04,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "alice@company.com",
    weekStart: "2025-11-24",
    messageSummaries: [
      {
        theme: "launch coordination",
        intent: "collaboration",
        sentiment: "positive",
        example:
          "Coordinated campaign analytics rollout with growth and marketing.",
      },
      {
        theme: "support",
        intent: "support",
        sentiment: "positive",
        example:
          "Helped resolve a prompt version mismatch for a live campaign.",
      },
      {
        theme: "alignment",
        intent: "collaboration",
        sentiment: "positive",
        example: "Aligned on template governance expectations for Q4.",
      },
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Shared a summary of render stability metrics.",
      },
    ],
    messageCount: 70,
    replyCount: 48,
    reactionsReceived: 42,
    afterHoursRatio: 0.04,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "alice@company.com",
    weekStart: "2025-12-01",
    messageSummaries: [
      {
        theme: "design discussion",
        intent: "collaboration",
        sentiment: "positive",
        example: "Led a thread on presenting prompt performance insights.",
      },
      {
        theme: "support",
        intent: "support",
        sentiment: "positive",
        example: "Assisted growth with campaign cost preview questions.",
      },
      {
        theme: "alignment",
        intent: "collaboration",
        sentiment: "positive",
        example: "Aligned with infra on render backoff changes.",
      },
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Posted weekly status on template versioning rollout.",
      },
    ],
    messageCount: 74,
    replyCount: 50,
    reactionsReceived: 45,
    afterHoursRatio: 0.04,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "alice@company.com",
    weekStart: "2025-12-08",
    messageSummaries: [
      {
        theme: "launch coordination",
        intent: "collaboration",
        sentiment: "positive",
        example:
          "Coordinated final rollout steps for adaptive quality renders.",
      },
      {
        theme: "support",
        intent: "support",
        sentiment: "positive",
        example: "Helped marketing validate new export formats.",
      },
      {
        theme: "design discussion",
        intent: "collaboration",
        sentiment: "positive",
        example: "Discussed prompt naming conventions across teams.",
      },
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Shared progress on render tracing improvements.",
      },
    ],
    messageCount: 78,
    replyCount: 52,
    reactionsReceived: 48,
    afterHoursRatio: 0.04,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "alice@company.com",
    weekStart: "2025-12-15",
    messageSummaries: [
      {
        theme: "alignment",
        intent: "collaboration",
        sentiment: "positive",
        example:
          "Aligned leadership on Q1 prompt personalization roadmap.",
      },
      {
        theme: "support",
        intent: "support",
        sentiment: "positive",
        example: "Helped resolve a campaign analytics question for growth.",
      },
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Posted a summary of platform stability work.",
      },
      {
        theme: "design discussion",
        intent: "collaboration",
        sentiment: "positive",
        example: "Captured learnings from prompt adoption feedback.",
      },
    ],
    messageCount: 81,
    replyCount: 55,
    reactionsReceived: 52,
    afterHoursRatio: 0.03,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "alice@company.com",
    weekStart: "2025-12-22",
    messageSummaries: [
      {
        theme: "launch coordination",
        intent: "collaboration",
        sentiment: "positive",
        example: "Coordinated year-end analytics snapshots with marketing.",
      },
      {
        theme: "support",
        intent: "support",
        sentiment: "positive",
        example: "Helped clarify prompt inheritance behavior for campaigns.",
      },
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Shared end-of-quarter platform highlights.",
      },
      {
        theme: "alignment",
        intent: "collaboration",
        sentiment: "positive",
        example: "Aligned cross-team expectations for post-holiday stability.",
      },
    ],
    messageCount: 85,
    replyCount: 58,
    reactionsReceived: 56,
    afterHoursRatio: 0.03,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "bob@company.com",
    weekStart: "2025-10-06",
    messageSummaries: [
      {
        theme: "launch coordination",
        intent: "collaboration",
        sentiment: "neutral",
        example: "Coordinated render capacity changes with infra.",
      },
      {
        theme: "support",
        intent: "support",
        sentiment: "neutral",
        example: "Helped debug a campaign render slowdown.",
      },
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Posted a status update on queue prioritization changes.",
      },
      {
        theme: "bug triage",
        intent: "support",
        sentiment: "neutral",
        example: "Escalated a render failure report for investigation.",
      },
    ],
    messageCount: 78,
    replyCount: 50,
    reactionsReceived: 38,
    afterHoursRatio: 0.25,
    weekendRatio: 0.1,
  },
  {
    employeeEmail: "bob@company.com",
    weekStart: "2025-10-13",
    messageSummaries: [
      {
        theme: "launch coordination",
        intent: "collaboration",
        sentiment: "neutral",
        example: "Synced on campaign reschedule steps with marketing.",
      },
      {
        theme: "support",
        intent: "support",
        sentiment: "neutral",
        example: "Provided guidance for handling render backlogs.",
      },
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Shared a status note on API fixes.",
      },
      {
        theme: "bug triage",
        intent: "support",
        sentiment: "neutral",
        example: "Acknowledged a timeout issue and tracked follow-up.",
      },
    ],
    messageCount: 80,
    replyCount: 48,
    reactionsReceived: 34,
    afterHoursRatio: 0.28,
    weekendRatio: 0.12,
  },
  {
    employeeEmail: "bob@company.com",
    weekStart: "2025-10-20",
    messageSummaries: [
      {
        theme: "launch coordination",
        intent: "collaboration",
        sentiment: "neutral",
        example: "Coordinated burst capacity with infra for campaign load.",
      },
      {
        theme: "support",
        intent: "support",
        sentiment: "neutral",
        example: "Helped triage billing discrepancies after retries.",
      },
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Posted an update on render worker changes.",
      },
      {
        theme: "bug triage",
        intent: "support",
        sentiment: "neutral",
        example: "Flagged a queue saturation issue for follow-up.",
      },
    ],
    messageCount: 82,
    replyCount: 46,
    reactionsReceived: 32,
    afterHoursRatio: 0.32,
    weekendRatio: 0.15,
  },
  {
    employeeEmail: "bob@company.com",
    weekStart: "2025-10-27",
    messageSummaries: [
      {
        theme: "launch coordination",
        intent: "collaboration",
        sentiment: "neutral",
        example: "Coordinated on-call response for launch week stability.",
      },
      {
        theme: "support",
        intent: "support",
        sentiment: "neutral",
        example: "Helped platform team validate render preset changes.",
      },
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Shared incident notes on queue ordering fixes.",
      },
    ],
    messageCount: 85,
    replyCount: 44,
    reactionsReceived: 28,
    afterHoursRatio: 0.35,
    weekendRatio: 0.18,
  },
  {
    employeeEmail: "bob@company.com",
    weekStart: "2025-11-03",
    messageSummaries: [
      {
        theme: "bug triage",
        intent: "blocking",
        sentiment: "neutral-negative",
        example: "Flagged a blocking render timeout during peak load.",
      },
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Posted a terse update on hotfix progress.",
      },
      {
        theme: "handoff",
        intent: "blocking",
        sentiment: "neutral-negative",
        example: "Handed off incident follow-up due to overlapping issues.",
      },
    ],
    messageCount: 78,
    replyCount: 38,
    reactionsReceived: 22,
    afterHoursRatio: 0.4,
    weekendRatio: 0.22,
  },
  {
    employeeEmail: "bob@company.com",
    weekStart: "2025-11-10",
    messageSummaries: [
      {
        theme: "blocker discussion",
        intent: "blocking",
        sentiment: "neutral-negative",
        example: "Called out a blocker in queue stability during rollout.",
      },
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Shared a short update on billing patch status.",
      },
      {
        theme: "handoff",
        intent: "blocking",
        sentiment: "neutral-negative",
        example: "Requested help covering late-night incident follow-up.",
      },
    ],
    messageCount: 70,
    replyCount: 30,
    reactionsReceived: 16,
    afterHoursRatio: 0.45,
    weekendRatio: 0.28,
  },
  {
    employeeEmail: "bob@company.com",
    weekStart: "2025-11-17",
    messageSummaries: [
      {
        theme: "blocker discussion",
        intent: "blocking",
        sentiment: "neutral-negative",
        example: "Escalated a recurring queue stall impacting campaigns.",
      },
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Posted a brief note on retry fix status.",
      },
    ],
    messageCount: 60,
    replyCount: 24,
    reactionsReceived: 12,
    afterHoursRatio: 0.5,
    weekendRatio: 0.32,
  },
  {
    employeeEmail: "bob@company.com",
    weekStart: "2025-11-24",
    messageSummaries: [
      {
        theme: "blocker discussion",
        intent: "blocking",
        sentiment: "neutral-negative",
        example: "Asked for help handling backlog spikes during holiday traffic.",
      },
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Shared a short summary of backlog status.",
      },
    ],
    messageCount: 48,
    replyCount: 18,
    reactionsReceived: 9,
    afterHoursRatio: 0.55,
    weekendRatio: 0.4,
  },
  {
    employeeEmail: "bob@company.com",
    weekStart: "2025-12-01",
    messageSummaries: [
      {
        theme: "handoff",
        intent: "blocking",
        sentiment: "neutral-negative",
        example: "Handed off remaining queue issues due to fatigue.",
      },
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Posted a brief update on API timeout patch.",
      },
    ],
    messageCount: 40,
    replyCount: 14,
    reactionsReceived: 7,
    afterHoursRatio: 0.6,
    weekendRatio: 0.45,
  },
  {
    employeeEmail: "bob@company.com",
    weekStart: "2025-12-08",
    messageSummaries: [
      {
        theme: "blocker discussion",
        intent: "blocking",
        sentiment: "neutral-negative",
        example: "Raised concern about weekend backlog coverage.",
      },
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Shared a minimal update on metrics changes.",
      },
    ],
    messageCount: 35,
    replyCount: 12,
    reactionsReceived: 6,
    afterHoursRatio: 0.58,
    weekendRatio: 0.42,
  },
  {
    employeeEmail: "bob@company.com",
    weekStart: "2025-12-15",
    messageSummaries: [
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Posted a short update on queue tweaks.",
      },
      {
        theme: "handoff",
        intent: "blocking",
        sentiment: "neutral-negative",
        example: "Requested backup for late-week incident checks.",
      },
    ],
    messageCount: 30,
    replyCount: 9,
    reactionsReceived: 4,
    afterHoursRatio: 0.6,
    weekendRatio: 0.5,
  },
  {
    employeeEmail: "bob@company.com",
    weekStart: "2025-12-22",
    messageSummaries: [
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral-negative",
        example: "Shared a brief note on lingering backlog issues.",
      },
      {
        theme: "passive",
        intent: "passive",
        sentiment: "neutral-negative",
        example: "Acknowledged updates without further follow-up.",
      },
    ],
    messageCount: 26,
    replyCount: 7,
    reactionsReceived: 3,
    afterHoursRatio: 0.62,
    weekendRatio: 0.52,
  },
  {
    employeeEmail: "carol@company.com",
    weekStart: "2025-10-06",
    messageSummaries: [
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Posted a short update that a UI tweak was ready.",
      },
      {
        theme: "passive",
        intent: "passive",
        sentiment: "neutral",
        example: "Acknowledged a campaign request without adding detail.",
      },
    ],
    messageCount: 12,
    replyCount: 3,
    reactionsReceived: 2,
    afterHoursRatio: 0.01,
    weekendRatio: 0.0,
  },
  {
    employeeEmail: "carol@company.com",
    weekStart: "2025-10-13",
    messageSummaries: [
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Shared a brief note about a small API change.",
      },
      {
        theme: "passive",
        intent: "passive",
        sentiment: "neutral",
        example: "Acknowledged a task assignment.",
      },
    ],
    messageCount: 10,
    replyCount: 2,
    reactionsReceived: 1,
    afterHoursRatio: 0.0,
    weekendRatio: 0.0,
  },
  {
    employeeEmail: "carol@company.com",
    weekStart: "2025-10-20",
    messageSummaries: [
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Posted a short update on copy tweaks.",
      },
    ],
    messageCount: 8,
    replyCount: 1,
    reactionsReceived: 1,
    afterHoursRatio: 0.0,
    weekendRatio: 0.0,
  },
  {
    employeeEmail: "carol@company.com",
    weekStart: "2025-10-27",
    messageSummaries: [
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Shared a note about a small UI fix.",
      },
      {
        theme: "passive",
        intent: "passive",
        sentiment: "neutral",
        example: "Acknowledged a request to review settings.",
      },
    ],
    messageCount: 13,
    replyCount: 3,
    reactionsReceived: 2,
    afterHoursRatio: 0.02,
    weekendRatio: 0.0,
  },
  {
    employeeEmail: "carol@company.com",
    weekStart: "2025-11-03",
    messageSummaries: [
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Posted a brief update on a minor label change.",
      },
    ],
    messageCount: 10,
    replyCount: 2,
    reactionsReceived: 1,
    afterHoursRatio: 0.01,
    weekendRatio: 0.0,
  },
  {
    employeeEmail: "carol@company.com",
    weekStart: "2025-11-10",
    messageSummaries: [
      {
        theme: "passive",
        intent: "passive",
        sentiment: "neutral",
        example: "Acknowledged the weekly check-in.",
      },
    ],
    messageCount: 9,
    replyCount: 1,
    reactionsReceived: 1,
    afterHoursRatio: 0.0,
    weekendRatio: 0.0,
  },
  {
    employeeEmail: "carol@company.com",
    weekStart: "2025-11-17",
    messageSummaries: [
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Shared a short note about a small cleanup.",
      },
    ],
    messageCount: 8,
    replyCount: 1,
    reactionsReceived: 1,
    afterHoursRatio: 0.0,
    weekendRatio: 0.0,
  },
  {
    employeeEmail: "carol@company.com",
    weekStart: "2025-11-24",
    messageSummaries: [
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Posted that a tiny API update was complete.",
      },
    ],
    messageCount: 11,
    replyCount: 2,
    reactionsReceived: 1,
    afterHoursRatio: 0.01,
    weekendRatio: 0.0,
  },
  {
    employeeEmail: "carol@company.com",
    weekStart: "2025-12-01",
    messageSummaries: [
      {
        theme: "passive",
        intent: "passive",
        sentiment: "neutral",
        example: "Acknowledged a request for help without follow-up.",
      },
    ],
    messageCount: 10,
    replyCount: 1,
    reactionsReceived: 1,
    afterHoursRatio: 0.0,
    weekendRatio: 0.0,
  },
  {
    employeeEmail: "carol@company.com",
    weekStart: "2025-12-08",
    messageSummaries: [
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Shared a short note on a minor copy change.",
      },
    ],
    messageCount: 7,
    replyCount: 1,
    reactionsReceived: 0,
    afterHoursRatio: 0.0,
    weekendRatio: 0.0,
  },
  {
    employeeEmail: "carol@company.com",
    weekStart: "2025-12-15",
    messageSummaries: [
      {
        theme: "passive",
        intent: "passive",
        sentiment: "neutral",
        example: "Acknowledged a status ping.",
      },
    ],
    messageCount: 6,
    replyCount: 1,
    reactionsReceived: 0,
    afterHoursRatio: 0.0,
    weekendRatio: 0.0,
  },
  {
    employeeEmail: "carol@company.com",
    weekStart: "2025-12-22",
    messageSummaries: [
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Posted a brief note about a small text fix.",
      },
    ],
    messageCount: 5,
    replyCount: 1,
    reactionsReceived: 0,
    afterHoursRatio: 0.0,
    weekendRatio: 0.0,
  },
  {
    employeeEmail: "dave@company.com",
    weekStart: "2025-10-06",
    messageSummaries: [
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Shared frequent updates on campaign readiness.",
      },
      {
        theme: "opinion sharing",
        intent: "passive",
        sentiment: "neutral",
        example:
          "Shared thoughts on campaign aesthetics without concrete actions.",
      },
    ],
    messageCount: 85,
    replyCount: 22,
    reactionsReceived: 10,
    afterHoursRatio: 0.18,
    weekendRatio: 0.06,
  },
  {
    employeeEmail: "dave@company.com",
    weekStart: "2025-10-13",
    messageSummaries: [
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Posted multiple check-ins asking for progress confirmation.",
      },
      {
        theme: "coordination",
        intent: "collaboration",
        sentiment: "neutral",
        example: "Asked others for timelines without owning tasks.",
      },
    ],
    messageCount: 88,
    replyCount: 20,
    reactionsReceived: 9,
    afterHoursRatio: 0.2,
    weekendRatio: 0.07,
  },
  {
    employeeEmail: "dave@company.com",
    weekStart: "2025-10-20",
    messageSummaries: [
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Shared daily updates summarizing meetings.",
      },
      {
        theme: "opinion sharing",
        intent: "passive",
        sentiment: "neutral",
        example: "Commented on prompt quality without follow-through.",
      },
    ],
    messageCount: 90,
    replyCount: 18,
    reactionsReceived: 8,
    afterHoursRatio: 0.22,
    weekendRatio: 0.08,
  },
  {
    employeeEmail: "dave@company.com",
    weekStart: "2025-10-27",
    messageSummaries: [
      {
        theme: "coordination",
        intent: "collaboration",
        sentiment: "neutral",
        example: "Pinged teams repeatedly to confirm rollout status.",
      },
    ],
    messageCount: 92,
    replyCount: 17,
    reactionsReceived: 7,
    afterHoursRatio: 0.24,
    weekendRatio: 0.09,
  },
  {
    employeeEmail: "dave@company.com",
    weekStart: "2025-11-03",
    messageSummaries: [
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Posted summaries of discussions without decisions.",
      },
    ],
    messageCount: 95,
    replyCount: 16,
    reactionsReceived: 6,
    afterHoursRatio: 0.25,
    weekendRatio: 0.1,
  },
  {
    employeeEmail: "dave@company.com",
    weekStart: "2025-11-10",
    messageSummaries: [
      {
        theme: "opinion sharing",
        intent: "passive",
        sentiment: "neutral",
        example: "Shared personal views on priorities without task ownership.",
      },
    ],
    messageCount: 93,
    replyCount: 14,
    reactionsReceived: 5,
    afterHoursRatio: 0.26,
    weekendRatio: 0.11,
  },
  {
    employeeEmail: "dave@company.com",
    weekStart: "2025-11-17",
    messageSummaries: [
      {
        theme: "coordination",
        intent: "collaboration",
        sentiment: "neutral",
        example: "Asked for updates on tasks owned by others.",
      },
    ],
    messageCount: 90,
    replyCount: 13,
    reactionsReceived: 5,
    afterHoursRatio: 0.27,
    weekendRatio: 0.11,
  },
  {
    employeeEmail: "dave@company.com",
    weekStart: "2025-11-24",
    messageSummaries: [
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Shared a long status recap without new insights.",
      },
    ],
    messageCount: 88,
    replyCount: 12,
    reactionsReceived: 4,
    afterHoursRatio: 0.28,
    weekendRatio: 0.12,
  },
  {
    employeeEmail: "dave@company.com",
    weekStart: "2025-12-01",
    messageSummaries: [
      {
        theme: "coordination",
        intent: "collaboration",
        sentiment: "neutral",
        example: "Pinged teams repeatedly ahead of deadlines.",
      },
    ],
    messageCount: 86,
    replyCount: 11,
    reactionsReceived: 4,
    afterHoursRatio: 0.29,
    weekendRatio: 0.12,
  },
  {
    employeeEmail: "dave@company.com",
    weekStart: "2025-12-08",
    messageSummaries: [
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Posted reminders and follow-ups.",
      },
    ],
    messageCount: 84,
    replyCount: 10,
    reactionsReceived: 3,
    afterHoursRatio: 0.3,
    weekendRatio: 0.13,
  },
  {
    employeeEmail: "dave@company.com",
    weekStart: "2025-12-15",
    messageSummaries: [
      {
        theme: "passive",
        intent: "passive",
        sentiment: "neutral",
        example: "Acknowledged updates without engagement.",
      },
    ],
    messageCount: 80,
    replyCount: 9,
    reactionsReceived: 2,
    afterHoursRatio: 0.32,
    weekendRatio: 0.14,
  },
  {
    employeeEmail: "dave@company.com",
    weekStart: "2025-12-22",
    messageSummaries: [
      {
        theme: "status update",
        intent: "status update",
        sentiment: "neutral",
        example: "Posted end-of-quarter summaries without actionable insights.",
      },
    ],
    messageCount: 78,
    replyCount: 8,
    reactionsReceived: 2,
    afterHoursRatio: 0.33,
    weekendRatio: 0.15,
  },
  {
    employeeEmail: "eve@company.com",
    weekStart: "2025-10-06",
    messageSummaries: [
      {
        theme: "support",
        intent: "support",
        sentiment: "neutral",
        example: "Answered a technical question about render behavior.",
      },
    ],
    messageCount: 18,
    replyCount: 6,
    reactionsReceived: 4,
    afterHoursRatio: 0.02,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "eve@company.com",
    weekStart: "2025-10-13",
    messageSummaries: [
      {
        theme: "support",
        intent: "support",
        sentiment: "neutral",
        example: "Helped clarify prompt normalization behavior.",
      },
    ],
    messageCount: 20,
    replyCount: 7,
    reactionsReceived: 5,
    afterHoursRatio: 0.02,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "eve@company.com",
    weekStart: "2025-10-20",
    messageSummaries: [
      {
        theme: "support",
        intent: "support",
        sentiment: "neutral",
        example: "Provided input on render latency investigation.",
      },
    ],
    messageCount: 19,
    replyCount: 7,
    reactionsReceived: 5,
    afterHoursRatio: 0.02,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "eve@company.com",
    weekStart: "2025-10-27",
    messageSummaries: [
      {
        theme: "support",
        intent: "support",
        sentiment: "neutral",
        example: "Shared insights on analytics consistency.",
      },
    ],
    messageCount: 21,
    replyCount: 8,
    reactionsReceived: 6,
    afterHoursRatio: 0.02,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "eve@company.com",
    weekStart: "2025-11-03",
    messageSummaries: [
      {
        theme: "support",
        intent: "support",
        sentiment: "neutral",
        example: "Helped debug a low-level metrics discrepancy.",
      },
    ],
    messageCount: 22,
    replyCount: 8,
    reactionsReceived: 6,
    afterHoursRatio: 0.02,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "eve@company.com",
    weekStart: "2025-11-10",
    messageSummaries: [
      {
        theme: "support",
        intent: "support",
        sentiment: "neutral",
        example: "Clarified API validation behavior for platform team.",
      },
    ],
    messageCount: 21,
    replyCount: 9,
    reactionsReceived: 7,
    afterHoursRatio: 0.02,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "eve@company.com",
    weekStart: "2025-11-17",
    messageSummaries: [
      {
        theme: "support",
        intent: "support",
        sentiment: "neutral",
        example: "Helped infra understand queue fairness implications.",
      },
    ],
    messageCount: 23,
    replyCount: 9,
    reactionsReceived: 7,
    afterHoursRatio: 0.02,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "eve@company.com",
    weekStart: "2025-11-24",
    messageSummaries: [
      {
        theme: "support",
        intent: "support",
        sentiment: "neutral",
        example: "Answered follow-up questions on prompt execution paths.",
      },
    ],
    messageCount: 22,
    replyCount: 9,
    reactionsReceived: 7,
    afterHoursRatio: 0.02,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "eve@company.com",
    weekStart: "2025-12-01",
    messageSummaries: [
      {
        theme: "support",
        intent: "support",
        sentiment: "neutral",
        example: "Helped validate fallback behavior for experimental modes.",
      },
    ],
    messageCount: 24,
    replyCount: 10,
    reactionsReceived: 8,
    afterHoursRatio: 0.02,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "eve@company.com",
    weekStart: "2025-12-08",
    messageSummaries: [
      {
        theme: "support",
        intent: "support",
        sentiment: "neutral",
        example: "Clarified tracing changes for observability.",
      },
    ],
    messageCount: 23,
    replyCount: 10,
    reactionsReceived: 8,
    afterHoursRatio: 0.02,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "eve@company.com",
    weekStart: "2025-12-15",
    messageSummaries: [
      {
        theme: "support",
        intent: "support",
        sentiment: "neutral",
        example: "Helped growth team interpret analytics normalization.",
      },
    ],
    messageCount: 25,
    replyCount: 11,
    reactionsReceived: 9,
    afterHoursRatio: 0.02,
    weekendRatio: 0.01,
  },
  {
    employeeEmail: "eve@company.com",
    weekStart: "2025-12-22",
    messageSummaries: [
      {
        theme: "support",
        intent: "support",
        sentiment: "neutral",
        example: "Answered a last-minute technical clarification.",
      },
    ],
    messageCount: 26,
    replyCount: 11,
    reactionsReceived: 9,
    afterHoursRatio: 0.02,
    weekendRatio: 0.01,
  },
];
